// Stuti Traders — Mock Data for Development

import { Product, Category, Customer, Order, DashboardStats, ActivityLog } from "@/types";

export const mockCategories: Category[] = [
  {
    id: "cat-1",
    name: "Kitchen & Cookware",
    slug: "kitchen-cookware",
    description: "Premium pressure cookers, cookware sets, utensils, and kitchen essentials",
    imageUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    sortOrder: 0,
    _count: { products: 14 },
  },
  {
    id: "cat-2",
    name: "Storage & Organisation",
    slug: "storage-organisation",
    description: "Containers, racks, shelves, and smart storage solutions for every room",
    imageUrl: "https://images.unsplash.com/photo-1616046229478-9901c5536a45?w=800&q=80",
    sortOrder: 1,
    _count: { products: 10 },
  },
  {
    id: "cat-3",
    name: "Cleaning Essentials",
    slug: "cleaning-essentials",
    description: "Brooms, mops, dusters, and everything you need for a spotless home",
    imageUrl: "https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?w=800&q=80",
    sortOrder: 2,
    _count: { products: 8 },
  },
  {
    id: "cat-4",
    name: "Bathroom & Laundry",
    slug: "bathroom-laundry",
    description: "Buckets, baskets, organisers, and accessories for bathroom and laundry",
    imageUrl: "https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800&q=80",
    sortOrder: 3,
    _count: { products: 9 },
  },
  {
    id: "cat-5",
    name: "Water Bottles & Flasks",
    slug: "water-bottles-flasks",
    description: "Stainless steel bottles, copper bottles, flasks, and hydration essentials",
    imageUrl: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&q=80",
    sortOrder: 4,
    _count: { products: 7 },
  },
  {
    id: "cat-6",
    name: "Home & Decor",
    slug: "home-decor",
    description: "Dustbins, hangers, hooks, organisers, and everyday home essentials",
    imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&q=80",
    sortOrder: 5,
    _count: { products: 12 },
  },
];

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    name: "Stainless Steel Pressure Cooker 5L",
    slug: "stainless-steel-pressure-cooker-5l",
    sku: "KIT-001",
    description: "A heavy-duty 5-litre stainless steel pressure cooker built for the Indian kitchen. Features a sturdy base for even heat distribution, ergonomic handles, and a precision-engineered safety valve. Perfect for daily cooking — from dal and rice to biryani and curries.",
    price: 1850,
    categoryId: "cat-1",
    category: { id: "cat-1", name: "Kitchen & Cookware", slug: "kitchen-cookware", description: null, imageUrl: null, sortOrder: 0 },
    status: "ACTIVE",
    specifications: {
      "Capacity": "5 Litres",
      "Material": "Stainless Steel (18/8)",
      "Base": "Tri-ply induction base",
      "Compatibility": "Gas, Induction, Electric",
      "Warranty": "5 Years",
      "Weight": "1.8 kg",
    },
    seoTitle: "Stainless Steel Pressure Cooker 5L | Stuti Traders",
    seoDescription: "Heavy-duty 5L stainless steel pressure cooker with tri-ply induction base. Perfect for Indian cooking.",
    images: [
      { id: "img-1", productId: "prod-1", url: "https://images.unsplash.com/photo-1622973536968-3ead9e780960?w=1200&q=80", alt: "Stainless Steel Pressure Cooker 5L", sortOrder: 0, isPrimary: true },
      { id: "img-2", productId: "prod-1", url: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=1200&q=80", alt: "Pressure Cooker — kitchen view", sortOrder: 1, isPrimary: false },
    ],
    createdAt: "2024-12-01T10:00:00Z",
    updatedAt: "2024-12-15T14:30:00Z",
  },
  {
    id: "prod-2",
    name: "Airtight Storage Container Set (5 Pcs)",
    slug: "airtight-storage-container-set-5pcs",
    sku: "STR-001",
    description: "Keep your kitchen organised with this set of 5 airtight containers in assorted sizes. Made from BPA-free food-grade plastic with snap-lock lids that keep contents fresh for longer. Ideal for storing pulses, rice, flour, spices, and snacks.",
    price: 699,
    categoryId: "cat-2",
    category: { id: "cat-2", name: "Storage & Organisation", slug: "storage-organisation", description: null, imageUrl: null, sortOrder: 1 },
    status: "ACTIVE",
    specifications: {
      "Set Contents": "500ml, 1L, 1.5L, 2L, 3L",
      "Material": "BPA-Free Food-Grade Plastic",
      "Lid Type": "Snap-lock Airtight",
      "Microwave Safe": "Yes (without lid)",
      "Dishwasher Safe": "Yes",
    },
    seoTitle: "Airtight Storage Container Set (5 Pcs) | Stuti Traders",
    seoDescription: "Set of 5 BPA-free airtight containers for kitchen storage. Keeps food fresh longer.",
    images: [
      { id: "img-3", productId: "prod-2", url: "https://images.unsplash.com/photo-1616046229478-9901c5536a45?w=1200&q=80", alt: "Airtight Storage Containers", sortOrder: 0, isPrimary: true },
      { id: "img-4", productId: "prod-2", url: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=1200&q=80", alt: "Storage Containers — stacked", sortOrder: 1, isPrimary: false },
    ],
    createdAt: "2024-11-20T10:00:00Z",
    updatedAt: "2024-12-10T09:00:00Z",
  },
  {
    id: "prod-3",
    name: "Stainless Steel Water Bottle 1L",
    slug: "stainless-steel-water-bottle-1l",
    sku: "BOT-001",
    description: "A sleek single-wall stainless steel water bottle that keeps your water pure and chemical-free. Leak-proof cap, lightweight design, and a mirror-polish finish that looks great anywhere — from your office desk to your gym bag.",
    price: 450,
    categoryId: "cat-5",
    category: { id: "cat-5", name: "Water Bottles & Flasks", slug: "water-bottles-flasks", description: null, imageUrl: null, sortOrder: 4 },
    status: "ACTIVE",
    specifications: {
      "Capacity": "1 Litre",
      "Material": "304 Stainless Steel",
      "Type": "Single Wall",
      "Lid": "Leak-proof Screw Cap",
      "Finish": "Mirror Polish",
      "Weight": "220g",
    },
    seoTitle: "Stainless Steel Water Bottle 1L | Stuti Traders",
    seoDescription: "Sleek 1L stainless steel water bottle with leak-proof cap. Chemical-free hydration on the go.",
    images: [
      { id: "img-5", productId: "prod-3", url: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=1200&q=80", alt: "Stainless Steel Water Bottle", sortOrder: 0, isPrimary: true },
      { id: "img-6", productId: "prod-3", url: "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=1200&q=80", alt: "Water Bottle — close-up", sortOrder: 1, isPrimary: false },
    ],
    createdAt: "2024-12-05T10:00:00Z",
    updatedAt: "2024-12-12T11:00:00Z",
  },
  {
    id: "prod-4",
    name: "Spin Mop with Bucket Set",
    slug: "spin-mop-with-bucket-set",
    sku: "CLN-001",
    description: "Make floor cleaning effortless with this 360° spin mop and wringer bucket set. The foot-pedal operated spinner wrings the mop hands-free, while the microfibre mop head picks up dust, dirt, and grime in a single pass. Includes 2 mop head refills.",
    price: 1299,
    categoryId: "cat-3",
    category: { id: "cat-3", name: "Cleaning Essentials", slug: "cleaning-essentials", description: null, imageUrl: null, sortOrder: 2 },
    status: "ACTIVE",
    specifications: {
      "Bucket Capacity": "10 Litres",
      "Mop Head": "Microfibre",
      "Spin": "360° Foot-pedal",
      "Handle": "Stainless Steel Extendable",
      "Refills Included": "2",
      "Color": "Blue / Grey",
    },
    seoTitle: "Spin Mop with Bucket Set | Stuti Traders",
    seoDescription: "360° spin mop with foot-pedal wringer bucket. Includes 2 microfibre refills for effortless cleaning.",
    images: [
      { id: "img-7", productId: "prod-4", url: "https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?w=1200&q=80", alt: "Spin Mop with Bucket", sortOrder: 0, isPrimary: true },
      { id: "img-8", productId: "prod-4", url: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=1200&q=80", alt: "Mop cleaning floor", sortOrder: 1, isPrimary: false },
    ],
    createdAt: "2024-11-15T10:00:00Z",
    updatedAt: "2024-12-01T08:00:00Z",
  },
  {
    id: "prod-5",
    name: "3-Tier Stainless Steel Tiffin Box",
    slug: "3-tier-stainless-steel-tiffin-box",
    sku: "KIT-002",
    description: "A classic 3-tier stainless steel tiffin carrier that keeps your meals fresh and leak-free. Each compartment is generously sized for roti, sabzi, and rice. Durable locking clips and a comfortable carry handle make it ideal for office, school, and travel.",
    price: 550,
    categoryId: "cat-1",
    category: { id: "cat-1", name: "Kitchen & Cookware", slug: "kitchen-cookware", description: null, imageUrl: null, sortOrder: 0 },
    status: "ACTIVE",
    specifications: {
      "Tiers": "3",
      "Material": "Stainless Steel",
      "Capacity per Tier": "350ml",
      "Locking": "Side Clips",
      "Handle": "Wire Carry Handle",
      "Leak-Proof": "Yes",
    },
    seoTitle: "3-Tier Stainless Steel Tiffin Box | Stuti Traders",
    seoDescription: "Classic 3-tier stainless steel tiffin carrier. Leak-proof, durable, perfect for office and school.",
    images: [
      { id: "img-9", productId: "prod-5", url: "https://images.unsplash.com/photo-1600857062241-98e5dba7f214?w=1200&q=80", alt: "3-Tier Tiffin Box", sortOrder: 0, isPrimary: true },
    ],
    createdAt: "2024-12-10T10:00:00Z",
    updatedAt: "2024-12-14T16:00:00Z",
  },
  {
    id: "prod-6",
    name: "Heavy Duty Plastic Bucket 20L",
    slug: "heavy-duty-plastic-bucket-20l",
    sku: "BAT-001",
    description: "A robust 20-litre bucket made from virgin-grade unbreakable plastic. Features a sturdy metal handle with comfortable grip, measurement markings on the inside, and a reinforced rim that won't crack. Essential for every bathroom and laundry room.",
    price: 299,
    categoryId: "cat-4",
    category: { id: "cat-4", name: "Bathroom & Laundry", slug: "bathroom-laundry", description: null, imageUrl: null, sortOrder: 3 },
    status: "ACTIVE",
    specifications: {
      "Capacity": "20 Litres",
      "Material": "Virgin-grade Plastic",
      "Handle": "Stainless Steel with Grip",
      "Markings": "Internal measurement lines",
      "Color": "Available in 4 colours",
    },
    seoTitle: "Heavy Duty Plastic Bucket 20L | Stuti Traders",
    seoDescription: "Unbreakable 20L heavy-duty plastic bucket with steel handle. Built for daily household use.",
    images: [
      { id: "img-10", productId: "prod-6", url: "https://images.unsplash.com/photo-1620626011761-996317b8d101?w=1200&q=80", alt: "Heavy Duty Bucket", sortOrder: 0, isPrimary: true },
    ],
    createdAt: "2024-11-28T10:00:00Z",
    updatedAt: "2024-12-08T10:00:00Z",
  },
  {
    id: "prod-7",
    name: "Copper Water Bottle 950ml",
    slug: "copper-water-bottle-950ml",
    sku: "BOT-002",
    description: "Handcrafted from pure copper with a beautiful hammered finish. Drinking water stored in copper is an age-old Ayurvedic practice known for its health benefits. Leak-proof threaded cap, lacquer-coated exterior to prevent tarnishing.",
    price: 799,
    categoryId: "cat-5",
    category: { id: "cat-5", name: "Water Bottles & Flasks", slug: "water-bottles-flasks", description: null, imageUrl: null, sortOrder: 4 },
    status: "ACTIVE",
    specifications: {
      "Capacity": "950ml",
      "Material": "Pure Copper",
      "Finish": "Hammered",
      "Coating": "Food-safe Lacquer (exterior)",
      "Lid": "Threaded Leak-proof",
      "Care": "Hand wash only",
    },
    seoTitle: "Copper Water Bottle 950ml | Stuti Traders",
    seoDescription: "Pure copper water bottle with hammered finish. 950ml, leak-proof, Ayurvedic health benefits.",
    images: [
      { id: "img-11", productId: "prod-7", url: "https://images.unsplash.com/photo-1570831739435-6601aa3fa4fb?w=1200&q=80", alt: "Copper Water Bottle", sortOrder: 0, isPrimary: true },
    ],
    createdAt: "2024-12-08T10:00:00Z",
    updatedAt: "2024-12-13T15:00:00Z",
  },
  {
    id: "prod-8",
    name: "Non-Stick Kadai with Glass Lid",
    slug: "non-stick-kadai-with-glass-lid",
    sku: "KIT-003",
    description: "A premium deep-fry kadai with 5-layer non-stick granite coating for oil-free cooking. The tempered glass lid lets you monitor cooking without losing heat. Induction compatible, with a cool-touch bakelite handle and a sturdy aluminium body.",
    price: 1150,
    categoryId: "cat-1",
    category: { id: "cat-1", name: "Kitchen & Cookware", slug: "kitchen-cookware", description: null, imageUrl: null, sortOrder: 0 },
    status: "ACTIVE",
    specifications: {
      "Size": "26 cm",
      "Material": "Die-cast Aluminium",
      "Coating": "5-Layer Granite Non-stick",
      "Lid": "Tempered Glass",
      "Handle": "Cool-touch Bakelite",
      "Compatibility": "Gas, Induction, Electric",
    },
    seoTitle: "Non-Stick Kadai with Glass Lid | Stuti Traders",
    seoDescription: "Premium 26cm non-stick kadai with granite coating and glass lid. Induction compatible.",
    images: [
      { id: "img-12", productId: "prod-8", url: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1200&q=80", alt: "Non-Stick Kadai", sortOrder: 0, isPrimary: true },
    ],
    createdAt: "2024-12-02T10:00:00Z",
    updatedAt: "2024-12-11T12:00:00Z",
  },
];

export const mockCustomers: Customer[] = [
  {
    id: "cust-1",
    name: "Priya Sharma",
    phone: "+91 98765 43210",
    whatsapp: "+919876543210",
    email: "priya.sharma@gmail.com",
    address: "B-12, Shanti Nagar, Andheri West, Mumbai 400058",
    notes: "Regular customer. Buys in bulk for her shop. Prefers COD.",
    createdAt: "2024-10-15T10:00:00Z",
    updatedAt: "2024-12-10T14:00:00Z",
    _count: { orders: 5 },
    totalRevenue: 18500,
  },
  {
    id: "cust-2",
    name: "Rajesh Patel",
    phone: "+91 87654 32109",
    whatsapp: "+918765432109",
    email: "rajesh.patel@yahoo.com",
    address: "15, Nehru Road, Navrangpura, Ahmedabad 380009",
    notes: "Hotel owner. Needs kitchenware in bulk quantities.",
    createdAt: "2024-11-02T10:00:00Z",
    updatedAt: "2024-12-14T09:00:00Z",
    _count: { orders: 3 },
    totalRevenue: 32400,
  },
  {
    id: "cust-3",
    name: "Anita Verma",
    phone: "+91 99887 65432",
    whatsapp: "+919988765432",
    email: "anita.verma@gmail.com",
    address: "C-45, Sector 22, Noida 201301",
    notes: "Repeat customer. Referred 3 new customers last month.",
    createdAt: "2024-09-20T10:00:00Z",
    updatedAt: "2024-12-12T16:00:00Z",
    _count: { orders: 7 },
    totalRevenue: 12800,
  },
  {
    id: "cust-4",
    name: "Suresh Kumar",
    phone: "+91 77889 90011",
    whatsapp: "+917788990011",
    email: "suresh.k@gmail.com",
    address: "22/A, MG Road, Indore 452001",
    notes: "New customer. Interested in bulk pricing for office supplies.",
    createdAt: "2024-12-01T10:00:00Z",
    updatedAt: "2024-12-13T11:00:00Z",
    _count: { orders: 1 },
    totalRevenue: 2550,
  },
];

export const mockOrders: Order[] = [
  {
    id: "ord-1",
    orderNumber: "ST-2024-001",
    customerId: "cust-1",
    customer: mockCustomers[0],
    status: "DELIVERED",
    subtotal: 5250,
    total: 5250,
    notes: "Deliver between 10am–1pm. Call before delivery.",
    items: [
      { id: "oi-1", orderId: "ord-1", productId: "prod-1", product: mockProducts[0], quantity: 2, unitPrice: 1850, totalPrice: 3700, notes: null },
      { id: "oi-2", orderId: "ord-1", productId: "prod-5", product: mockProducts[4], quantity: 2, unitPrice: 550, totalPrice: 1100, notes: null },
      { id: "oi-3", orderId: "ord-1", productId: "prod-3", product: mockProducts[2], quantity: 1, unitPrice: 450, totalPrice: 450, notes: null },
    ],
    statusHistory: [
      { id: "sh-1", orderId: "ord-1", fromStatus: null, toStatus: "INQUIRY", notes: "Customer enquired via WhatsApp", changedBy: { name: "Admin" }, createdAt: "2024-11-01T10:00:00Z" },
      { id: "sh-2", orderId: "ord-1", fromStatus: "INQUIRY", toStatus: "QUOTATION_SENT", notes: "Quotation shared on WhatsApp", changedBy: { name: "Admin" }, createdAt: "2024-11-02T09:00:00Z" },
      { id: "sh-3", orderId: "ord-1", fromStatus: "QUOTATION_SENT", toStatus: "CONFIRMED", notes: "Customer confirmed via call", changedBy: { name: "Admin" }, createdAt: "2024-11-05T14:00:00Z" },
      { id: "sh-4", orderId: "ord-1", fromStatus: "CONFIRMED", toStatus: "PROCESSING", notes: "Packing order", changedBy: { name: "Admin" }, createdAt: "2024-11-06T10:00:00Z" },
      { id: "sh-5", orderId: "ord-1", fromStatus: "PROCESSING", toStatus: "DELIVERED", notes: "Delivered. COD collected ₹5,250", changedBy: { name: "Admin" }, createdAt: "2024-11-08T16:00:00Z" },
    ],
    createdAt: "2024-11-01T10:00:00Z",
    updatedAt: "2024-11-08T16:00:00Z",
  },
  {
    id: "ord-2",
    orderNumber: "ST-2024-002",
    customerId: "cust-2",
    customer: mockCustomers[1],
    status: "PROCESSING",
    subtotal: 15350,
    total: 15350,
    notes: "Bulk order for hotel. Needs delivery to back entrance.",
    items: [
      { id: "oi-4", orderId: "ord-2", productId: "prod-1", product: mockProducts[0], quantity: 5, unitPrice: 1850, totalPrice: 9250, notes: "5L size" },
      { id: "oi-5", orderId: "ord-2", productId: "prod-8", product: mockProducts[7], quantity: 4, unitPrice: 1150, totalPrice: 4600, notes: "26cm kadai" },
      { id: "oi-6", orderId: "ord-2", productId: "prod-5", product: mockProducts[4], quantity: 3, unitPrice: 550, totalPrice: 1500, notes: null },
    ],
    statusHistory: [
      { id: "sh-6", orderId: "ord-2", fromStatus: null, toStatus: "INQUIRY", notes: "Referred by another customer", changedBy: { name: "Admin" }, createdAt: "2024-11-20T10:00:00Z" },
      { id: "sh-7", orderId: "ord-2", fromStatus: "INQUIRY", toStatus: "CONFIRMED", notes: "Confirmed with advance payment", changedBy: { name: "Admin" }, createdAt: "2024-11-21T09:00:00Z" },
      { id: "sh-8", orderId: "ord-2", fromStatus: "CONFIRMED", toStatus: "PROCESSING", notes: "Items being packed", changedBy: { name: "Admin" }, createdAt: "2024-11-25T11:00:00Z" },
    ],
    createdAt: "2024-11-20T10:00:00Z",
    updatedAt: "2024-11-25T11:00:00Z",
  },
  {
    id: "ord-3",
    orderNumber: "ST-2024-003",
    customerId: "cust-3",
    customer: mockCustomers[2],
    status: "QUOTATION_SENT",
    subtotal: 3397,
    total: 3397,
    notes: null,
    items: [
      { id: "oi-7", orderId: "ord-3", productId: "prod-4", product: mockProducts[3], quantity: 1, unitPrice: 1299, totalPrice: 1299, notes: null },
      { id: "oi-8", orderId: "ord-3", productId: "prod-2", product: mockProducts[1], quantity: 2, unitPrice: 699, totalPrice: 1398, notes: null },
      { id: "oi-9", orderId: "ord-3", productId: "prod-6", product: mockProducts[5], quantity: 2, unitPrice: 299, totalPrice: 598, notes: "Blue colour" },
    ],
    statusHistory: [
      { id: "sh-9", orderId: "ord-3", fromStatus: null, toStatus: "INQUIRY", notes: "Via Instagram DM", changedBy: { name: "Admin" }, createdAt: "2024-12-10T10:00:00Z" },
      { id: "sh-10", orderId: "ord-3", fromStatus: "INQUIRY", toStatus: "QUOTATION_SENT", notes: "Price list sent on WhatsApp", changedBy: { name: "Admin" }, createdAt: "2024-12-11T09:00:00Z" },
    ],
    createdAt: "2024-12-10T10:00:00Z",
    updatedAt: "2024-12-11T09:00:00Z",
  },
  {
    id: "ord-4",
    orderNumber: "ST-2024-004",
    customerId: "cust-4",
    customer: mockCustomers[3],
    status: "INQUIRY",
    subtotal: 2550,
    total: 2550,
    notes: "Wants to see samples before ordering.",
    items: [
      { id: "oi-10", orderId: "ord-4", productId: "prod-7", product: mockProducts[6], quantity: 2, unitPrice: 799, totalPrice: 1598, notes: null },
      { id: "oi-11", orderId: "ord-4", productId: "prod-3", product: mockProducts[2], quantity: 2, unitPrice: 450, totalPrice: 900, notes: null },
    ],
    statusHistory: [
      { id: "sh-11", orderId: "ord-4", fromStatus: null, toStatus: "INQUIRY", notes: "Phone inquiry — wants bulk pricing", changedBy: { name: "Admin" }, createdAt: "2024-12-14T10:00:00Z" },
    ],
    createdAt: "2024-12-14T10:00:00Z",
    updatedAt: "2024-12-14T10:00:00Z",
  },
];

export const mockActivityLogs: ActivityLog[] = [
  { id: "log-1", userId: "user-1", user: { name: "Admin" }, action: "created", entityType: "order", entityId: "ord-4", metadata: { orderNumber: "ST-2024-004" }, createdAt: "2024-12-14T10:00:00Z" },
  { id: "log-2", userId: "user-1", user: { name: "Admin" }, action: "updated_status", entityType: "order", entityId: "ord-3", metadata: { from: "INQUIRY", to: "QUOTATION_SENT" }, createdAt: "2024-12-11T09:00:00Z" },
  { id: "log-3", userId: "user-1", user: { name: "Admin" }, action: "created", entityType: "product", entityId: "prod-8", metadata: { name: "Non-Stick Kadai with Glass Lid" }, createdAt: "2024-12-10T10:00:00Z" },
  { id: "log-4", userId: "user-1", user: { name: "Admin" }, action: "created", entityType: "customer", entityId: "cust-4", metadata: { name: "Suresh Kumar" }, createdAt: "2024-12-01T10:00:00Z" },
  { id: "log-5", userId: "user-1", user: { name: "Admin" }, action: "updated_status", entityType: "order", entityId: "ord-1", metadata: { from: "PROCESSING", to: "DELIVERED" }, createdAt: "2024-11-08T16:00:00Z" },
];

export const mockDashboardStats: DashboardStats = {
  totalProducts: 8,
  totalCustomers: 4,
  totalOrders: 4,
  revenueThisMonth: 26547,
  recentOrders: mockOrders.slice(0, 4),
  recentActivity: mockActivityLogs,
};
